### ISSUE TITLE
Upload fails with large file, works with smaller ones (nondescriptive readerror)

### ISSUE THREAD

**Issue by JulianRein** [gdcc/python-dvuploader#47]
Hi there, 

I am using easyDataverse and thus pydvuploader. 
However, when uploading a "larger" 2.1 GB file (fastq.gz), the upload stalls and fails with a "ReadError" and nothing else.
It works for smaller files in the same directory.
It also fails when renaming the file to remove the .fastq.gz
Likely unrelated: wierd filenames like "index.html?C=N;O=D" also fail. Here, renaming helps.

Any idea how to solve this? 
I attached the (very long) error log, which unfortunately does not help me at all. (to avoid confusion: streamlit is the name of my conda-env, it does not run as an actual webapp at the moment, but in an .ipynb within positron. 
However, running it in a standard console throws the same error -> both example runs attached)

My code (besides the console run):

`
import dvuploader as dv

path = "testProjectX/SDFSF_3232423_24R388-1_S143_L000_R2_001.fastq.gz" (large file)
"#path = "uploadCode.tmp" WORKED (small file)"
"# path = "testProjectX/exampleHtml2" # WORKED (small file) "
"# path = "testProjectX/index.html?C=D;O=D" did NOT work (small file)"
"# path = "testProjectX/R2fastqCopied.fastq.gz" NOT working either... takes too long?" (large file)
"# path = "testProjectX/R2fastqCopied" # Nope..." (large file)

"# Add file individually"
files = [
    dv.File(directory_label="fastq", filepath=path, tab_ingest = False),
]

dvuploader = dv.DVUploader(files=files)
dvuploader.upload(
    api_token=dataset.API_TOKEN,
    dataverse_url=dataset.DATAVERSE_URL,
    persistent_id=dataset.p_id,
    n_parallel_uploads=1, # Whatever your instance can handle
`

[longErrorPyDVuploader.txt](https://github.com/user-attachments/files/22519708/longErrorPyDVuploader.txt)

**Comment by JR-1991** [comment]
@JulianRein, thank you for submitting the issue. I was able to replicate the error even locally. Upon closer inspection of the passed file handlers, including a sanity check for size and correctness, I found that the correct file is being passed to the request library. I suspect that this is not a specific issue with `python-dvuploader`, but rather with either `httpx` or Dataverse itself.

I’ll check if the issue works on previous Dataverse versions. If it does, we can exclude this as the source of the problem. It’s possible that larger files are restricted because Dataverse recommends HTTP-based uploads up to 2GB. In general, it’s advisable to use the S3 direct upload (which is also supported here) to upload larger volumes, as HTTP uploads can be unreliable with large files.

I’ll get back to you once I have more information.

**Comment by JulianRein** [comment]
@JR-1991 Thanks again for the quick reaction. 
As a side note: I did (try to) increase the dataverse file limit to > 5GB with below command, to no avail:
> curl -X PUT -d 6000000000 http://localhost:8080/api/admin/settings/:MaxFileUploadSizeInBytes
> {"status":"OK","data":{":MaxFileUploadSizeInBytes":"6000000000"}}

**Comment by JR-1991** [comment]
@JulianRein I have added an intermediate streaming layer to track the upload progress, because somehow with the new `httpx` version this did not work as before, and it seemed to have resolved the error (local and remote). I suspect that the `ReadError` has stemmed from too frequent readouts, causing an error, but I am not sure. I will put this more to the test and will get back to you with a PR to test on your machine.

**Comment by JR-1991** [comment]
@JulianRein apologies for my delayed response, could not get back earlier. I’ve pushed the changes that resolved the error locally to a new branch and opened a new draft pull request (#48) for testing. Can you try it again with these changes?

**Comment by JR-1991** [comment]
@JulianRein, thanks for the feedback!

Upon reviewing the files you’ve uploaded, the TSV file might trigger a dataset lock, preventing any retries initiated by `tenacity`. Although you’ve explicitly stated that you don’t want to perform tabular ingestion, there was a recent bug that caused the tab ingest to fail. This bug was fixed and merged into the `main` branch in #46, but this branch hasn’t been updated yet. I’ve merged the `main` branch with the fix into this PR.

Could you try uploading the files with and without the TSV file to ensure that this isn’t a general issue? I’ve tested a 2GB mock file on our Stuttgart instance, and the upload works. So, I believe this might be the solution to this problem. :)

**Comment by JulianRein** [comment]
@JR-1991 Thanks for the quick reply!
I deleted the .tsv and the .tab from the project, see below. (I assumed that I should just test, not update to the new ingestion-fix PR).
However, the hangup still persists with the same error. Is there any use to try it on a new project? Any other ideas?

<img width="848" height="785" alt="Image" src="https://github.com/user-attachments/assets/de5b3aaf-bbfc-48d9-8462-3aa7c51dc4a6" />

**Comment by JulianRein** [comment]
Thanks a lot for testing this. Yes, in the last run I have also seen that the server restarted after the upload failed. 
With production environment, I assume you mean the non-docker install of dataverse?
I would open a dataverse-issue then.
